# Generated by Django 4.1.4 on 2023-02-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixelpictures", "0003_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(upload_to="pictures/"),
        ),
    ]
