# Generated by Django 4.1.4 on 2023-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixelpictures", "0005_alter_picture_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
