# Generated by Django 4.1.4 on 2023-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixelpictures", "0007_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture", name="palette", field=models.JSONField(default=list),
        ),
    ]
